lang:
  error: "&cAn unknown exception occurred, please report this to staff!"
  player-only: "&cYou must be a player to execute this command!"
  reload: "&aSuccessfully reloaded the plugin!"
  reload-fail: "&cThere was an error reloading the plugin! Please review the console for more information."
  no-pvp: "&cYou are not allowed to damage players during grace period!"
  unknown-command: "&cThis is not a valid command, please use &4/scavenger help &cfor help!"

  game-starting: "&aThe game is starting in &2%remaining% &aseconds!"
  game-started: "&2&l✔ &a&lGAME STARTED! &f— &aBest of luck everyone!"

  pvp-enable: "&6⚠ &cPVP will be enabled in: &4%remaining% seconds!"
  pvp-enabled: "&c\n&c\n&6⚠ &lWARNING&f: &cPVP is now enabled!\n&c"

  no-world-provided: "&cYou must provide a world when starting a game from the console!"
  game-in-progress: "&cThis world already has a game in progress!"
  game-not-in-progress: "&cYou are not in a game currently!"

  no-item-provided: "&cYou must provide an item!"
  incorrect-item-provided: "&cThis item is not required for this round!"
  item-already-provided: "&cYou have already added this item!"
  item-not-enough: "&cYou need &4%required% &cof this item, you currently only have &%required%&c! "
  item-accepted: "&aCongrats, you now have &2%current% &aout of &2%total%&a items!"
  items-left: "&7Items left: &3%items%"

  help-lines:
    - "&c"
    - "&8&m                                                                               &r"
    - "<g:#13425E:#0A6EAB>&lAPEX HOSTING&f: &r&#40B350Scavenger Hunt"
    - "&cPlease do note that the plugin is currently work in progress."
    - "&c"
    - " &r• &#B94A4D/%command% help &7—&f Here you are!"
    - " &r• &#B94A4D/%command% start <template> &7—&f Start a new game"
    - " &r• &#B94A4D/%command% cheat &7—&f Cheat in all the items for testing"
    - " &r• &#B94A4D/%command% stop &7—&f Force stop the currently running game"
    - " &r• &#B94A4D/%command% reload &7—&f Stop all games, reload all configuration values"
    - "&8&m                                                                               &r"

games:
  my_game:
    displayname: "&d&lMy Amazing Game"

    # The amount of players to wait for, set to -1 to only forcestart it
    required-players: -1

    # Whether players are put into spectator when they die
    hardcore: false

    pvp-bossbar:
      enabled: true
      title: "&bPVP will be enabled in: &3%remaining% &bseconds!"
      colour: auto

    drop-items:
      on-pvp-kill: true
      on-natural-death: true

    scoreboard:
      enabled: true
      title: "&7-=[&6&lLeaderboard&7]=-"
      line-format: "&7#%place%) &#fed256%playername%&f &7(&f%returncount% &7items)"
      show-players: 10

    # Where dead players respawn
    spawnpoint:
      world: world
      x: 12
      y: 65
      z: 12

    return-gui: # currently doing: 2022/01/18 (Tuesday) 19:01:28

    return-npcs:
      notmydoug:
        displayname: "Not Doug, smh"
        skin: "Notch"
        world: world
        look-close: false
        x: 10
        y: 65
        z: 10

      doug:
        displayname: "&8[&cNPC&8] &rDoug"
        skin: "ApexHosting"
        world: world
        look-close: true
        x: 0
        y: 65
        z: 0

    # Given in minutes, set it to 0 to enable PVP on start, -1 to disable PVP
    grace-period: 3

    # The size of the worldborder
    border-size: 500
    border-center:
      x: 0
      z: 0

    # How many completers to wait for
    winners: 3

    # The allowed worlds for the game
    worlds:
      - world
      - world_nether
      - world_the_end

    starter-items:
      book:
        material: WRITTEN_BOOK
        name: "&4&lStarter Instructions"
        hide-enchants: true
        enchantments:
          mending: 1
        author: "&cDoug"
        type: original
        pages:
          1: |
            Welcome to ApexHosting's Scavenger Hunt event!

            The first 3 to complete the hunt get an amazon gift card as well as free hosting!

            ➜
      #•➜
      stone_axe_yes:
        enchants:
          efficiency: 5
          unbreaking: 3
          mending: 2
        material: STONE_AXE
        lore:
          - "stonks"
          - "&chello!"

    # The required items for someone to win
    required-items:
      enchanting_table:
        material: ENCHANTING_TABLE
      anvil:
        material: ANVIL
      golden_apple:
        material: GOLDEN_APPLE
      cornflower:
        material: CORNFLOWER
      tnt:
        material: TNT
      lectern:
        material: LECTERN
      mushroom_stew:
        material: MUSHROOM_STEW
      egg:
        material: EGG
      bread:
        material: BREAD